name: Display Issue \#${{ github.event.issue.number }} Event Details

on:
  issues:
    types:
      - opened

jobs:
  show-issue-details:
    runs-on: ubuntu-latest

    steps:
    - name: Print event details
      run: |
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "Issue body: ${{ github.event.issue.body }}"
        echo "Created by: ${{ github.event.issue.user.login }}"
