name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Minify html, css and js files
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Use "static-website-minifier-workflow" Action
        uses: pabcrudel/static-website-minifier-workflow@main
        with:
          project_path: www
          artifact_name: "github-pages"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
            
