name: Test Workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move into folder
        run: cd www

      - name: Minify Workflow
        uses: pabcrudel/static-website-minifier-workflow@main

      - name: Checkout
        run: ls
  minify:
    uses: pabcrudel/static-website-minifier-workflow@main