name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    name: Minify & Deploy
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Minify html, css and js files
        uses: pabcrudel/static-website-minifier-workflow@main
        with:
          project_path: www

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: dist  
