name: Test Workflows

on:
  push:
    branches:
      - main

jobs:
  minify:
    uses: pabcrudel/static-website-minifier-workflow/.github/workflows/minify.yml@main
    with:
      project_path: ./www

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: ls -la
