name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Minify html, css and js files
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Use Static Website Minifier Workflow Action
        uses: pabcrudel/static-website-minifier-workflow@main
        with:
          project_path: www
          artifact_name: minified-website

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Download Minified Files
        uses: actions/download-artifact@v3
        with:
          name: minified-website
          path: .
          
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: .
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2
          
