name: Test Workflows

on:
  push:
    branches:
      - main

jobs:
  minify:
    uses: pabcrudel/static-website-minifier-workflow/.github/workflows/minify.yml@main
    with:
      project_path: ./www
