name: Minify Static Website

on:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Minify and Save to Dist Folder
        uses: pabcrudel/static-website-minifier-workflow@v1
        with:
          project_path: './www'

      - name: Test
        run: ls -la ./www
