name: Test Workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Minify Workflow
        uses: pabcrudel/static-website-minifier-workflow