name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Minify html, css and js files
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Use "static-website-minifier-workflow" Action
        uses: pabcrudel/static-website-minifier-workflow@feature/minify-script
        # with:
        #   project_path: www